// @@@LICENSE
//
//      Copyright (c) 2010-2012 Hewlett-Packard Development Company, L.P.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// LICENSE@@@

// Generated by Grammar Analyzer
#ifndef __PARSER_H__
#define __PARSER_H__

enum TokenType {
	TK_ERROR
	, TK_LPAREN
	, TK_RPAREN
	, TK_PERIOD
	, TK_LT
	, TK_GT
	, TK_BODY
	, TK_BODYSTRUCTURE
	, TK_ENVELOPE
	, TK_EXPUNGE
	, TK_FETCH
	, TK_FLAGS
	, TK_HEADER
	, TK_HEADER_DOT_FIELDS
	, TK_HEADER_DOT_FIELDS_DOT_NOT
	, TK_INTERNALDATE
	, TK_MIME
	, TK_NIL
	, TK_RFC822
	, TK_RFC822_DOT_HEADER
	, TK_RFC822_DOT_SIZE
	, TK_RFC822_DOT_TEXT
	, TK_TEXT
	, TK_UID
	, TK_LBRACKET
	, TK_BACKSLASH
	, TK_NOT_Recent
	, TK_RBRACKET
	, TK_LBRACE
	, TK_RBRACE
	, TK_ATOM
	, TK_CR
	, TK_LF
	, TK_LITERAL_BYTES
	, TK_MESSAGE_IN_QUOTES
	, TK_NUMBER
	, TK_QUOTED_STRING
	, TK_QUOTED_STRING_WITHOUT_TERMINATION
	, TK_RFC822_IN_QUOTES
	, TK_SP
	, TK_TEXT_IN_QUOTES
	, TK_addr_adl
	, TK_addr_host
	, TK_addr_mailbox
	, TK_addr_name
	, TK_address
	, TK_astring
	, TK_atom_as_string
	, TK_body
	, TK_body_ext_1part
	, TK_body_ext_mpart
	, TK_body_extension
	, TK_body_fields
	, TK_body_fld_desc
	, TK_body_fld_dsp
	, TK_body_fld_enc
	, TK_body_fld_id
	, TK_body_fld_lang
	, TK_body_fld_lines
	, TK_body_fld_loc
	, TK_body_fld_md5
	, TK_body_fld_octets
	, TK_body_fld_param
	, TK_body_type_1part
	, TK_body_type_basic
	, TK_body_type_mpart
	, TK_body_type_msg
	, TK_body_type_text
	, TK_date_time
	, TK_env_bcc
	, TK_env_cc
	, TK_env_date
	, TK_env_from
	, TK_env_in_reply_to
	, TK_env_message_id
	, TK_env_reply_to
	, TK_env_sender
	, TK_env_subject
	, TK_env_to
	, TK_envelope
	, TK_flag
	, TK_flag_extension
	, TK_flag_fetch
	, TK_flag_keyword
	, TK_goal
	, TK_header_fld_name
	, TK_header_list
	, TK_km_address_list_or_nil
	, TK_km_body_ext_1part
	, TK_km_body_fld_after_dsp
	, TK_km_body_fld_after_lang
	, TK_km_body_fld_after_md5
	, TK_km_body_or_sect
	, TK_km_body_type
	, TK_km_body_type_basic_or_workaround
	, TK_km_body_type_choices
	, TK_km_body_type_msg_ext
	, TK_km_body_type_msg_ext_gmail
	, TK_km_body_type_msg_ext_rfc822
	, TK_km_body_type_msg_rfc822
	, TK_km_body_type_or_ext_mpart
	, TK_km_flag_fetch_parts
	, TK_km_message_subtype_more
	, TK_km_more_body_extension
	, TK_km_more_body_fld_lang
	, TK_km_more_body_fld_param
	, TK_km_more_flag_fetch
	, TK_km_more_header_field_names
	, TK_km_more_msg_att
	, TK_km_one_or_more_address
	, TK_km_one_or_more_bodies
	, TK_km_one_part_or_mpart
	, TK_km_opt_body_extension
	, TK_km_opt_body_fld_dsp
	, TK_km_opt_body_fld_lang
	, TK_km_opt_body_fld_loc
	, TK_km_optional_body_ext_mpart
	, TK_km_optional_dot_section_text
	, TK_km_optional_section_spec
	, TK_km_section_number
	, TK_km_section_part_and_text
	, TK_km_section_sub_part
	, TK_km_zero_or_more_address
	, TK_km_zero_or_more_bodies
	, TK_km_expunge_or_fetch
	, TK_km_fetch
	, TK_km_msg_att_dynamic_or_static
	, TK_literal
	, TK_media_basic
	, TK_media_message
	, TK_media_subtype
	, TK_media_text
	, TK_message_data
	, TK_msg_att
	, TK_msg_att_dynamic
	, TK_msg_att_static
	, TK_nil
	, TK_nstring
	, TK_nz_number
	, TK_quoted_string
	, TK_section
	, TK_section_msgtext
	, TK_section_part
	, TK_section_spec
	, TK_section_text
	, TK_single_body_fld_param
	, TK_string
	, TK_uniqueid
};
#endif /* __PARSER_H__ */
