// Generated by Grammar Analyzer

// @@@LICENSE
//
//      Copyright (c) 2009-2013 LG Electronics, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// LICENSE@@@

#include <list>
#include <map>
#include "parser/ImapParser.h"
#include "parser/ParserTypes.h"
#include "parser/SemanticActions.h"
using namespace std;



//Symbols:
static Symbol TT_ERROR("TT_ERROR",TK_ERROR,true);
static Symbol TT_LPAREN("TT_LPAREN",TK_LPAREN,true);
static Symbol TT_RPAREN("TT_RPAREN",TK_RPAREN,true);
static Symbol TT_PERIOD("TT_PERIOD",TK_PERIOD,true);
static Symbol TT_LT("TT_LT",TK_LT,true);
static Symbol TT_GT("TT_GT",TK_GT,true);
static Symbol TT_BODY("TT_BODY",TK_BODY,true);
static Symbol TT_BODYSTRUCTURE("TT_BODYSTRUCTURE",TK_BODYSTRUCTURE,true);
static Symbol TT_ENVELOPE("TT_ENVELOPE",TK_ENVELOPE,true);
static Symbol TT_EXPUNGE("TT_EXPUNGE",TK_EXPUNGE,true);
static Symbol TT_FETCH("TT_FETCH",TK_FETCH,true);
static Symbol TT_FLAGS("TT_FLAGS",TK_FLAGS,true);
static Symbol TT_HEADER("TT_HEADER",TK_HEADER,true);
static Symbol TT_HEADER_DOT_FIELDS("TT_HEADER_DOT_FIELDS",TK_HEADER_DOT_FIELDS,true);
static Symbol TT_HEADER_DOT_FIELDS_DOT_NOT("TT_HEADER_DOT_FIELDS_DOT_NOT",TK_HEADER_DOT_FIELDS_DOT_NOT,true);
static Symbol TT_INTERNALDATE("TT_INTERNALDATE",TK_INTERNALDATE,true);
static Symbol TT_MIME("TT_MIME",TK_MIME,true);
static Symbol TT_NIL("TT_NIL",TK_NIL,true);
static Symbol TT_RFC822("TT_RFC822",TK_RFC822,true);
static Symbol TT_RFC822_DOT_HEADER("TT_RFC822_DOT_HEADER",TK_RFC822_DOT_HEADER,true);
static Symbol TT_RFC822_DOT_SIZE("TT_RFC822_DOT_SIZE",TK_RFC822_DOT_SIZE,true);
static Symbol TT_RFC822_DOT_TEXT("TT_RFC822_DOT_TEXT",TK_RFC822_DOT_TEXT,true);
static Symbol TT_TEXT("TT_TEXT",TK_TEXT,true);
static Symbol TT_UID("TT_UID",TK_UID,true);
static Symbol TT_LBRACKET("TT_LBRACKET",TK_LBRACKET,true);
static Symbol TT_BACKSLASH("TT_BACKSLASH",TK_BACKSLASH,true);
static Symbol TT_NOT_Recent("TT_NOT_Recent",TK_NOT_Recent,true);
static Symbol TT_RBRACKET("TT_RBRACKET",TK_RBRACKET,true);
static Symbol TT_LBRACE("TT_LBRACE",TK_LBRACE,true);
static Symbol TT_RBRACE("TT_RBRACE",TK_RBRACE,true);
static Symbol TT_ATOM("TT_ATOM",TK_ATOM,true);
static Symbol TT_CR("TT_CR",TK_CR,true);
static Symbol TT_LF("TT_LF",TK_LF,true);
static Symbol TT_LITERAL_BYTES("TT_LITERAL_BYTES",TK_LITERAL_BYTES,true);
static Symbol TT_MESSAGE_IN_QUOTES("TT_MESSAGE_IN_QUOTES",TK_MESSAGE_IN_QUOTES,true);
static Symbol TT_NUMBER("TT_NUMBER",TK_NUMBER,true);
static Symbol TT_QUOTED_STRING("TT_QUOTED_STRING",TK_QUOTED_STRING,true);
static Symbol TT_QUOTED_STRING_WITHOUT_TERMINATION("TT_QUOTED_STRING_WITHOUT_TERMINATION",TK_QUOTED_STRING_WITHOUT_TERMINATION,true);
static Symbol TT_RFC822_IN_QUOTES("TT_RFC822_IN_QUOTES",TK_RFC822_IN_QUOTES,true);
static Symbol TT_SP("TT_SP",TK_SP,true);
static Symbol TT_TEXT_IN_QUOTES("TT_TEXT_IN_QUOTES",TK_TEXT_IN_QUOTES,true);
static Symbol NT_addr_adl("NT_addr_adl",TK_addr_adl,false);
static Symbol NT_addr_host("NT_addr_host",TK_addr_host,false);
static Symbol NT_addr_mailbox("NT_addr_mailbox",TK_addr_mailbox,false);
static Symbol NT_addr_name("NT_addr_name",TK_addr_name,false);
static Symbol NT_address("NT_address",TK_address,false);
static Symbol NT_astring("NT_astring",TK_astring,false);
static Symbol NT_atom_as_string("NT_atom_as_string",TK_atom_as_string,false);
static Symbol NT_body("NT_body",TK_body,false);
static Symbol NT_body_ext_1part("NT_body_ext_1part",TK_body_ext_1part,false);
static Symbol NT_body_ext_mpart("NT_body_ext_mpart",TK_body_ext_mpart,false);
static Symbol NT_body_extension("NT_body_extension",TK_body_extension,false);
static Symbol NT_body_fields("NT_body_fields",TK_body_fields,false);
static Symbol NT_body_fld_desc("NT_body_fld_desc",TK_body_fld_desc,false);
static Symbol NT_body_fld_dsp("NT_body_fld_dsp",TK_body_fld_dsp,false);
static Symbol NT_body_fld_enc("NT_body_fld_enc",TK_body_fld_enc,false);
static Symbol NT_body_fld_id("NT_body_fld_id",TK_body_fld_id,false);
static Symbol NT_body_fld_lang("NT_body_fld_lang",TK_body_fld_lang,false);
static Symbol NT_body_fld_lines("NT_body_fld_lines",TK_body_fld_lines,false);
static Symbol NT_body_fld_loc("NT_body_fld_loc",TK_body_fld_loc,false);
static Symbol NT_body_fld_md5("NT_body_fld_md5",TK_body_fld_md5,false);
static Symbol NT_body_fld_octets("NT_body_fld_octets",TK_body_fld_octets,false);
static Symbol NT_body_fld_param("NT_body_fld_param",TK_body_fld_param,false);
static Symbol NT_body_type_1part("NT_body_type_1part",TK_body_type_1part,false);
static Symbol NT_body_type_basic("NT_body_type_basic",TK_body_type_basic,false);
static Symbol NT_body_type_mpart("NT_body_type_mpart",TK_body_type_mpart,false);
static Symbol NT_body_type_msg("NT_body_type_msg",TK_body_type_msg,false);
static Symbol NT_body_type_text("NT_body_type_text",TK_body_type_text,false);
static Symbol NT_date_time("NT_date_time",TK_date_time,false);
static Symbol NT_env_bcc("NT_env_bcc",TK_env_bcc,false);
static Symbol NT_env_cc("NT_env_cc",TK_env_cc,false);
static Symbol NT_env_date("NT_env_date",TK_env_date,false);
static Symbol NT_env_from("NT_env_from",TK_env_from,false);
static Symbol NT_env_in_reply_to("NT_env_in_reply_to",TK_env_in_reply_to,false);
static Symbol NT_env_message_id("NT_env_message_id",TK_env_message_id,false);
static Symbol NT_env_reply_to("NT_env_reply_to",TK_env_reply_to,false);
static Symbol NT_env_sender("NT_env_sender",TK_env_sender,false);
static Symbol NT_env_subject("NT_env_subject",TK_env_subject,false);
static Symbol NT_env_to("NT_env_to",TK_env_to,false);
static Symbol NT_envelope("NT_envelope",TK_envelope,false);
static Symbol NT_flag("NT_flag",TK_flag,false);
static Symbol NT_flag_extension("NT_flag_extension",TK_flag_extension,false);
static Symbol NT_flag_fetch("NT_flag_fetch",TK_flag_fetch,false);
static Symbol NT_flag_keyword("NT_flag_keyword",TK_flag_keyword,false);
static Symbol NT_goal("NT_goal",TK_goal,false);
static Symbol NT_header_fld_name("NT_header_fld_name",TK_header_fld_name,false);
static Symbol NT_header_list("NT_header_list",TK_header_list,false);
static Symbol NT_km_address_list_or_nil("NT_km_address_list_or_nil",TK_km_address_list_or_nil,false);
static Symbol NT_km_body_ext_1part("NT_km_body_ext_1part",TK_km_body_ext_1part,false);
static Symbol NT_km_body_fld_after_dsp("NT_km_body_fld_after_dsp",TK_km_body_fld_after_dsp,false);
static Symbol NT_km_body_fld_after_lang("NT_km_body_fld_after_lang",TK_km_body_fld_after_lang,false);
static Symbol NT_km_body_fld_after_md5("NT_km_body_fld_after_md5",TK_km_body_fld_after_md5,false);
static Symbol NT_km_body_or_sect("NT_km_body_or_sect",TK_km_body_or_sect,false);
static Symbol NT_km_body_type("NT_km_body_type",TK_km_body_type,false);
static Symbol NT_km_body_type_basic_or_workaround("NT_km_body_type_basic_or_workaround",TK_km_body_type_basic_or_workaround,false);
static Symbol NT_km_body_type_choices("NT_km_body_type_choices",TK_km_body_type_choices,false);
static Symbol NT_km_body_type_msg_ext("NT_km_body_type_msg_ext",TK_km_body_type_msg_ext,false);
static Symbol NT_km_body_type_msg_ext_gmail("NT_km_body_type_msg_ext_gmail",TK_km_body_type_msg_ext_gmail,false);
static Symbol NT_km_body_type_msg_ext_rfc822("NT_km_body_type_msg_ext_rfc822",TK_km_body_type_msg_ext_rfc822,false);
static Symbol NT_km_body_type_msg_rfc822("NT_km_body_type_msg_rfc822",TK_km_body_type_msg_rfc822,false);
static Symbol NT_km_body_type_or_ext_mpart("NT_km_body_type_or_ext_mpart",TK_km_body_type_or_ext_mpart,false);
static Symbol NT_km_flag_fetch_parts("NT_km_flag_fetch_parts",TK_km_flag_fetch_parts,false);
static Symbol NT_km_message_subtype_more("NT_km_message_subtype_more",TK_km_message_subtype_more,false);
static Symbol NT_km_more_body_extension("NT_km_more_body_extension",TK_km_more_body_extension,false);
static Symbol NT_km_more_body_fld_lang("NT_km_more_body_fld_lang",TK_km_more_body_fld_lang,false);
static Symbol NT_km_more_body_fld_param("NT_km_more_body_fld_param",TK_km_more_body_fld_param,false);
static Symbol NT_km_more_flag_fetch("NT_km_more_flag_fetch",TK_km_more_flag_fetch,false);
static Symbol NT_km_more_header_field_names("NT_km_more_header_field_names",TK_km_more_header_field_names,false);
static Symbol NT_km_more_msg_att("NT_km_more_msg_att",TK_km_more_msg_att,false);
static Symbol NT_km_one_or_more_address("NT_km_one_or_more_address",TK_km_one_or_more_address,false);
static Symbol NT_km_one_or_more_bodies("NT_km_one_or_more_bodies",TK_km_one_or_more_bodies,false);
static Symbol NT_km_one_part_or_mpart("NT_km_one_part_or_mpart",TK_km_one_part_or_mpart,false);
static Symbol NT_km_opt_body_extension("NT_km_opt_body_extension",TK_km_opt_body_extension,false);
static Symbol NT_km_opt_body_fld_dsp("NT_km_opt_body_fld_dsp",TK_km_opt_body_fld_dsp,false);
static Symbol NT_km_opt_body_fld_lang("NT_km_opt_body_fld_lang",TK_km_opt_body_fld_lang,false);
static Symbol NT_km_opt_body_fld_loc("NT_km_opt_body_fld_loc",TK_km_opt_body_fld_loc,false);
static Symbol NT_km_optional_body_ext_mpart("NT_km_optional_body_ext_mpart",TK_km_optional_body_ext_mpart,false);
static Symbol NT_km_optional_dot_section_text("NT_km_optional_dot_section_text",TK_km_optional_dot_section_text,false);
static Symbol NT_km_optional_section_spec("NT_km_optional_section_spec",TK_km_optional_section_spec,false);
static Symbol NT_km_section_number("NT_km_section_number",TK_km_section_number,false);
static Symbol NT_km_section_part_and_text("NT_km_section_part_and_text",TK_km_section_part_and_text,false);
static Symbol NT_km_section_sub_part("NT_km_section_sub_part",TK_km_section_sub_part,false);
static Symbol NT_km_zero_or_more_address("NT_km_zero_or_more_address",TK_km_zero_or_more_address,false);
static Symbol NT_km_zero_or_more_bodies("NT_km_zero_or_more_bodies",TK_km_zero_or_more_bodies,false);
static Symbol NT_km_expunge_or_fetch("NT_km_expunge_or_fetch",TK_km_expunge_or_fetch,false);
static Symbol NT_km_fetch("NT_km_fetch",TK_km_fetch,false);
static Symbol NT_km_msg_att_dynamic_or_static("NT_km_msg_att_dynamic_or_static",TK_km_msg_att_dynamic_or_static,false);
static Symbol NT_literal("NT_literal",TK_literal,false);
static Symbol NT_media_basic("NT_media_basic",TK_media_basic,false);
static Symbol NT_media_message("NT_media_message",TK_media_message,false);
static Symbol NT_media_subtype("NT_media_subtype",TK_media_subtype,false);
static Symbol NT_media_text("NT_media_text",TK_media_text,false);
static Symbol NT_message_data("NT_message_data",TK_message_data,false);
static Symbol NT_msg_att("NT_msg_att",TK_msg_att,false);
static Symbol NT_msg_att_dynamic("NT_msg_att_dynamic",TK_msg_att_dynamic,false);
static Symbol NT_msg_att_static("NT_msg_att_static",TK_msg_att_static,false);
static Symbol NT_nil("NT_nil",TK_nil,false);
static Symbol NT_nstring("NT_nstring",TK_nstring,false);
static Symbol NT_nz_number("NT_nz_number",TK_nz_number,false);
static Symbol NT_quoted_string("NT_quoted_string",TK_quoted_string,false);
static Symbol NT_section("NT_section",TK_section,false);
static Symbol NT_section_msgtext("NT_section_msgtext",TK_section_msgtext,false);
static Symbol NT_section_part("NT_section_part",TK_section_part,false);
static Symbol NT_section_spec("NT_section_spec",TK_section_spec,false);
static Symbol NT_section_text("NT_section_text",TK_section_text,false);
static Symbol NT_single_body_fld_param("NT_single_body_fld_param",TK_single_body_fld_param,false);
static Symbol NT_string("NT_string",TK_string,false);
static Symbol NT_uniqueid("NT_uniqueid",TK_uniqueid,false);


//Productions:
static Term termset_0[] = {
	  Term(&NT_message_data, NULL )
	};

static Production production_0( 0, &NT_goal, termset_0, 1, NULL);

static Term termset_1[] = {
	  Term(&NT_nz_number,  &SemanticActions::saveMsgNum )
	, Term(&TT_SP, NULL )
	, Term(&NT_km_expunge_or_fetch, NULL )
	};

static Production production_1( 1, &NT_message_data, termset_1, 3, NULL);

static Term termset_2[] = {
	  Term(&TT_EXPUNGE, NULL )
	};

static Production production_2( 2, &NT_km_expunge_or_fetch, termset_2, 1, NULL);

static Term termset_3[] = {
	  Term(&NT_km_fetch, NULL )
	};

static Production production_3( 3, &NT_km_expunge_or_fetch, termset_3, 1, NULL);

static Term termset_4[] = {
	  Term(&TT_FETCH, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_msg_att,  &SemanticActions::endFetch )
	};

static Production production_4( 4, &NT_km_fetch, termset_4, 3, NULL);

static Term termset_5[] = {
	  Term(&TT_LPAREN, NULL )
	, Term(&NT_km_msg_att_dynamic_or_static, NULL )
	, Term(&NT_km_more_msg_att, NULL )
	, Term(&TT_RPAREN, NULL )
	};

static Production production_5( 5, &NT_msg_att, termset_5, 4, NULL);

static Term termset_6[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_km_msg_att_dynamic_or_static, NULL )
	, Term(&NT_km_more_msg_att, NULL )
	};

static Production production_6( 6, &NT_km_more_msg_att, termset_6, 3, NULL);

static Term termset_7[] = {
	};

static Production production_7( 7, &NT_km_more_msg_att, termset_7, 0, NULL);

static Term termset_8[] = {
	  Term(&NT_msg_att_dynamic, NULL )
	};

static Production production_8( 8, &NT_km_msg_att_dynamic_or_static, termset_8, 1, NULL);

static Term termset_9[] = {
	  Term(&NT_msg_att_static, NULL )
	};

static Production production_9( 9, &NT_km_msg_att_dynamic_or_static, termset_9, 1, NULL);

static Term termset_10[] = {
	  Term(&TT_FLAGS,  &SemanticActions::beginFlags )
	, Term(&TT_SP, NULL )
	, Term(&TT_LPAREN, NULL )
	, Term(&NT_km_flag_fetch_parts, NULL )
	, Term(&TT_RPAREN, NULL )
	};

static Production production_10( 10, &NT_msg_att_dynamic, termset_10, 5, NULL);

static Term termset_11[] = {
	  Term(&NT_flag_fetch, NULL )
	, Term(&NT_km_more_flag_fetch, NULL )
	};

static Production production_11( 11, &NT_km_flag_fetch_parts, termset_11, 2, NULL);

static Term termset_12[] = {
	};

static Production production_12( 12, &NT_km_flag_fetch_parts, termset_12, 0, NULL);

static Term termset_13[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_flag_fetch, NULL )
	, Term(&NT_km_more_flag_fetch, NULL )
	};

static Production production_13( 13, &NT_km_more_flag_fetch, termset_13, 3, NULL);

static Term termset_14[] = {
	};

static Production production_14( 14, &NT_km_more_flag_fetch, termset_14, 0, NULL);

static Term termset_15[] = {
	  Term(&TT_ENVELOPE, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_envelope, NULL )
	};

static Production production_15( 15, &NT_msg_att_static, termset_15, 3, NULL);

static Term termset_16[] = {
	  Term(&TT_INTERNALDATE, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_date_time, NULL )
	};

static Production production_16( 16, &NT_msg_att_static, termset_16, 3, NULL);

static Term termset_17[] = {
	  Term(&TT_RFC822, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_nstring, NULL )
	};

static Production production_17( 17, &NT_msg_att_static, termset_17, 3, NULL);

static Term termset_18[] = {
	  Term(&TT_RFC822_DOT_HEADER, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_nstring, NULL )
	};

static Production production_18( 18, &NT_msg_att_static, termset_18, 3, NULL);

static Term termset_19[] = {
	  Term(&TT_RFC822_DOT_TEXT, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_nstring, NULL )
	};

static Production production_19( 19, &NT_msg_att_static, termset_19, 3, NULL);

static Term termset_20[] = {
	  Term(&TT_RFC822_DOT_SIZE, NULL )
	, Term(&TT_SP, NULL )
	, Term(&TT_NUMBER, NULL )
	};

static Production production_20( 20, &NT_msg_att_static, termset_20, 3, NULL);

static Term termset_21[] = {
	  Term(&TT_BODYSTRUCTURE, NULL )
	, Term(&TT_SP,  &SemanticActions::beginBodyStructure )
	, Term(&NT_body,  &SemanticActions::endBodyStructure )
	};

static Production production_21( 21, &NT_msg_att_static, termset_21, 3, NULL);

static Term termset_22[] = {
	  Term(&TT_BODY, NULL )
	, Term(&NT_km_body_or_sect,  &SemanticActions::handleBodyData )
	};

static Production production_22( 22, &NT_msg_att_static, termset_22, 2, NULL);

static Term termset_23[] = {
	  Term(&TT_UID, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_uniqueid, NULL )
	};

static Production production_23( 23, &NT_msg_att_static, termset_23, 3, NULL);

static Term termset_24[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body, NULL )
	};

static Production production_24( 24, &NT_km_body_or_sect, termset_24, 2, NULL);

static Term termset_25[] = {
	  Term(&NT_section, NULL )
	, Term(&NT_km_section_number, NULL )
	, Term(&TT_SP,  &SemanticActions::expectBodyData )
	, Term(&NT_nstring, NULL )
	};

static Production production_25( 25, &NT_km_body_or_sect, termset_25, 4, NULL);

static Term termset_26[] = {
	  Term(&TT_LT, NULL )
	, Term(&TT_NUMBER, NULL )
	, Term(&TT_GT, NULL )
	};

static Production production_26( 26, &NT_km_section_number, termset_26, 3, NULL);

static Term termset_27[] = {
	};

static Production production_27( 27, &NT_km_section_number, termset_27, 0, NULL);

static Term termset_28[] = {
	  Term(&TT_LPAREN, NULL )
	, Term(&NT_km_one_part_or_mpart, NULL )
	, Term(&TT_RPAREN, NULL )
	};

static Production production_28( 28, &NT_body, termset_28, 3, NULL);

static Term termset_29[] = {
	  Term(&NT_body_type_1part, NULL )
	};

static Production production_29( 29, &NT_km_one_part_or_mpart, termset_29, 1, NULL);

static Term termset_30[] = {
	  Term(&NT_body_type_mpart,  &SemanticActions::endPartSet )
	};

static Production production_30( 30, &NT_km_one_part_or_mpart, termset_30, 1,  &SemanticActions::beginPartSet);

static Term termset_31[] = {
	  Term(&NT_km_body_type_choices, NULL )
	};

static Production production_31( 31, &NT_body_type_1part, termset_31, 1, NULL);

static Term termset_32[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_ext_1part, NULL )
	};

static Production production_32( 32, &NT_km_body_ext_1part, termset_32, 2, NULL);

static Term termset_33[] = {
	};

static Production production_33( 33, &NT_km_body_ext_1part, termset_33, 0, NULL);

static Term termset_34[] = {
	  Term(&NT_km_body_type_basic_or_workaround, NULL )
	};

static Production production_34( 34, &NT_km_body_type_choices, termset_34, 1, NULL);

static Term termset_35[] = {
	  Term(&NT_body_type_msg, NULL )
	};

static Production production_35( 35, &NT_km_body_type_choices, termset_35, 1, NULL);

static Term termset_36[] = {
	  Term(&NT_body_type_text, NULL )
	};

static Production production_36( 36, &NT_km_body_type_choices, termset_36, 1, NULL);

static Term termset_37[] = {
	  Term(&NT_media_basic, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fields, NULL )
	, Term(&NT_km_body_ext_1part, NULL )
	};

static Production production_37( 37, &NT_body_type_basic, termset_37, 4, NULL);

static Term termset_38[] = {
	  Term(&NT_quoted_string,  &SemanticActions::setMimeType )
	, Term(&TT_SP, NULL )
	, Term(&NT_km_body_type_or_ext_mpart, NULL )
	};

static Production production_38( 38, &NT_km_body_type_basic_or_workaround, termset_38, 3, NULL);

static Term termset_39[] = {
	  Term(&NT_km_body_type, NULL )
	};

static Production production_39( 39, &NT_km_body_type_or_ext_mpart, termset_39, 1, NULL);

static Term termset_40[] = {
	  Term(&NT_body_ext_mpart,  &SemanticActions::zeroPartWorkaround )
	};

static Production production_40( 40, &NT_km_body_type_or_ext_mpart, termset_40, 1, NULL);

static Term termset_41[] = {
	  Term(&NT_quoted_string,  &SemanticActions::setMimeSubtype )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fields, NULL )
	, Term(&NT_km_body_ext_1part, NULL )
	};

static Production production_41( 41, &NT_km_body_type, termset_41, 4, NULL);

static Term termset_42[] = {
	  Term(&NT_body_fld_param, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fld_id, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fld_desc, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fld_enc, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fld_octets, NULL )
	};

static Production production_42( 42, &NT_body_fields, termset_42, 9, NULL);

static Term termset_43[] = {
	  Term(&TT_LPAREN, NULL )
	, Term(&NT_string,  &SemanticActions::setPartDisposition )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fld_param, NULL )
	, Term(&TT_RPAREN, NULL )
	};

static Production production_43( 43, &NT_body_fld_dsp, termset_43, 5, NULL);

static Term termset_44[] = {
	  Term(&NT_nil, NULL )
	};

static Production production_44( 44, &NT_body_fld_dsp, termset_44, 1, NULL);

static Term termset_45[] = {
	  Term(&NT_body_fld_md5, NULL )
	, Term(&NT_km_body_fld_after_md5, NULL )
	};

static Production production_45( 45, &NT_body_ext_1part, termset_45, 2, NULL);

static Term termset_46[] = {
	  Term(&NT_body_fld_param, NULL )
	, Term(&NT_km_opt_body_fld_dsp, NULL )
	};

static Production production_46( 46, &NT_body_ext_mpart, termset_46, 2, NULL);

static Term termset_47[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_fld_dsp, NULL )
	, Term(&NT_km_opt_body_fld_lang, NULL )
	};

static Production production_47( 47, &NT_km_opt_body_fld_dsp, termset_47, 3, NULL);

static Term termset_48[] = {
	};

static Production production_48( 48, &NT_km_opt_body_fld_dsp, termset_48, 0, NULL);

static Term termset_49[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_fld_lang, NULL )
	, Term(&NT_km_opt_body_fld_loc, NULL )
	};

static Production production_49( 49, &NT_km_opt_body_fld_lang, termset_49, 3, NULL);

static Term termset_50[] = {
	};

static Production production_50( 50, &NT_km_opt_body_fld_lang, termset_50, 0, NULL);

static Term termset_51[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_fld_loc, NULL )
	, Term(&NT_km_opt_body_extension, NULL )
	};

static Production production_51( 51, &NT_km_opt_body_fld_loc, termset_51, 3, NULL);

static Term termset_52[] = {
	};

static Production production_52( 52, &NT_km_opt_body_fld_loc, termset_52, 0, NULL);

static Term termset_53[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_extension, NULL )
	, Term(&NT_km_opt_body_extension, NULL )
	};

static Production production_53( 53, &NT_km_opt_body_extension, termset_53, 3, NULL);

static Term termset_54[] = {
	};

static Production production_54( 54, &NT_km_opt_body_extension, termset_54, 0, NULL);

static Term termset_55[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_fld_dsp, NULL )
	, Term(&NT_km_body_fld_after_dsp, NULL )
	};

static Production production_55( 55, &NT_km_body_fld_after_md5, termset_55, 3, NULL);

static Term termset_56[] = {
	};

static Production production_56( 56, &NT_km_body_fld_after_md5, termset_56, 0, NULL);

static Term termset_57[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_fld_lang, NULL )
	, Term(&NT_km_body_fld_after_lang, NULL )
	};

static Production production_57( 57, &NT_km_body_fld_after_dsp, termset_57, 3, NULL);

static Term termset_58[] = {
	};

static Production production_58( 58, &NT_km_body_fld_after_dsp, termset_58, 0, NULL);

static Term termset_59[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_fld_loc, NULL )
	, Term(&NT_km_more_body_extension, NULL )
	};

static Production production_59( 59, &NT_km_body_fld_after_lang, termset_59, 3, NULL);

static Term termset_60[] = {
	};

static Production production_60( 60, &NT_km_body_fld_after_lang, termset_60, 0, NULL);

static Term termset_61[] = {
	  Term(&NT_nstring, NULL )
	};

static Production production_61( 61, &NT_body_extension, termset_61, 1, NULL);

static Term termset_62[] = {
	  Term(&TT_NUMBER, NULL )
	};

static Production production_62( 62, &NT_body_extension, termset_62, 1, NULL);

static Term termset_63[] = {
	  Term(&TT_LPAREN, NULL )
	, Term(&NT_body_extension, NULL )
	, Term(&NT_km_more_body_extension, NULL )
	, Term(&TT_RPAREN, NULL )
	};

static Production production_63( 63, &NT_body_extension, termset_63, 4, NULL);

static Term termset_64[] = {
	};

static Production production_64( 64, &NT_body_extension, termset_64, 0, NULL);

static Term termset_65[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_extension, NULL )
	, Term(&NT_km_more_body_extension, NULL )
	};

static Production production_65( 65, &NT_km_more_body_extension, termset_65, 3, NULL);

static Term termset_66[] = {
	};

static Production production_66( 66, &NT_km_more_body_extension, termset_66, 0, NULL);

static Term termset_67[] = {
	  Term(&NT_nstring, NULL )
	};

static Production production_67( 67, &NT_body_fld_desc, termset_67, 1, NULL);

static Term termset_68[] = {
	  Term(&NT_string, NULL )
	};

static Production production_68( 68, &NT_nstring, termset_68, 1, NULL);

static Term termset_69[] = {
	  Term(&NT_nil,  &SemanticActions::saveNullString )
	};

static Production production_69( 69, &NT_nstring, termset_69, 1, NULL);

static Term termset_70[] = {
	  Term(&TT_NIL, NULL )
	};

static Production production_70( 70, &NT_nil, termset_70, 1, NULL);

static Term termset_71[] = {
	  Term(&TT_QUOTED_STRING,  &SemanticActions::saveQuotedString )
	};

static Production production_71( 71, &NT_quoted_string, termset_71, 1, NULL);

static Term termset_72[] = {
	  Term(&TT_QUOTED_STRING,  &SemanticActions::saveQuotedString )
	};

static Production production_72( 72, &NT_string, termset_72, 1, NULL);

static Term termset_73[] = {
	  Term(&TT_TEXT_IN_QUOTES,  &SemanticActions::saveQuotedString )
	};

static Production production_73( 73, &NT_string, termset_73, 1, NULL);

static Term termset_74[] = {
	  Term(&TT_RFC822_IN_QUOTES,  &SemanticActions::saveQuotedString )
	};

static Production production_74( 74, &NT_string, termset_74, 1, NULL);

static Term termset_75[] = {
	  Term(&TT_MESSAGE_IN_QUOTES,  &SemanticActions::saveQuotedString )
	};

static Production production_75( 75, &NT_string, termset_75, 1, NULL);

static Term termset_76[] = {
	  Term(&NT_literal,  &SemanticActions::saveLiteralString )
	};

static Production production_76( 76, &NT_string, termset_76, 1, NULL);

static Term termset_77[] = {
	  Term(&TT_LBRACE, NULL )
	, Term(&TT_NUMBER,  &SemanticActions::readAheadLiteral )
	, Term(&TT_RBRACE, NULL )
	, Term(&TT_CR, NULL )
	, Term(&TT_LF, NULL )
	, Term(&TT_LITERAL_BYTES,  &SemanticActions::endLiteralBytes )
	};

static Production production_77( 77, &NT_literal, termset_77, 6, NULL);

static Term termset_78[] = {
	  Term(&TT_NUMBER,  &SemanticActions::saveNonZeroNumber )
	};

static Production production_78( 78, &NT_nz_number, termset_78, 1, NULL);

static Term termset_79[] = {
	  Term(&TT_NUMBER,  &SemanticActions::saveUID )
	};

static Production production_79( 79, &NT_uniqueid, termset_79, 1, NULL);

static Term termset_80[] = {
	  Term(&TT_QUOTED_STRING,  &SemanticActions::saveInternalDate )
	};

static Production production_80( 80, &NT_date_time, termset_80, 1, NULL);

static Term termset_81[] = {
	  Term(&NT_flag_keyword, NULL )
	};

static Production production_81( 81, &NT_flag, termset_81, 1, NULL);

static Term termset_82[] = {
	  Term(&NT_flag_extension, NULL )
	};

static Production production_82( 82, &NT_flag, termset_82, 1, NULL);

static Term termset_83[] = {
	  Term(&TT_BACKSLASH, NULL )
	, Term(&TT_ATOM,  &SemanticActions::systemFlagAtom )
	};

static Production production_83( 83, &NT_flag_extension, termset_83, 2, NULL);

static Term termset_84[] = {
	  Term(&NT_flag, NULL )
	};

static Production production_84( 84, &NT_flag_fetch, termset_84, 1, NULL);

static Term termset_85[] = {
	  Term(&TT_NOT_Recent, NULL )
	};

static Production production_85( 85, &NT_flag_fetch, termset_85, 1, NULL);

static Term termset_86[] = {
	  Term(&TT_ATOM,  &SemanticActions::keywordFlagAtom )
	};

static Production production_86( 86, &NT_flag_keyword, termset_86, 1, NULL);

static Term termset_87[] = {
	  Term(&NT_string,  &SemanticActions::setContentEncoding )
	};

static Production production_87( 87, &NT_body_fld_enc, termset_87, 1, NULL);

static Term termset_88[] = {
	  Term(&NT_nil, NULL )
	};

static Production production_88( 88, &NT_body_fld_enc, termset_88, 1, NULL);

static Term termset_89[] = {
	  Term(&NT_nstring,  &SemanticActions::setContentId )
	};

static Production production_89( 89, &NT_body_fld_id, termset_89, 1, NULL);

static Term termset_90[] = {
	  Term(&NT_nstring, NULL )
	};

static Production production_90( 90, &NT_body_fld_lang, termset_90, 1, NULL);

static Term termset_91[] = {
	  Term(&TT_LPAREN, NULL )
	, Term(&NT_string, NULL )
	, Term(&NT_km_more_body_fld_lang, NULL )
	, Term(&TT_RPAREN, NULL )
	};

static Production production_91( 91, &NT_body_fld_lang, termset_91, 4, NULL);

static Term termset_92[] = {
	};

static Production production_92( 92, &NT_body_fld_lang, termset_92, 0, NULL);

static Term termset_93[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_string, NULL )
	, Term(&NT_km_more_body_fld_lang, NULL )
	};

static Production production_93( 93, &NT_km_more_body_fld_lang, termset_93, 3, NULL);

static Term termset_94[] = {
	};

static Production production_94( 94, &NT_km_more_body_fld_lang, termset_94, 0, NULL);

static Term termset_95[] = {
	  Term(&TT_NUMBER, NULL )
	};

static Production production_95( 95, &NT_body_fld_lines, termset_95, 1, NULL);

static Term termset_96[] = {
	  Term(&NT_nstring, NULL )
	};

static Production production_96( 96, &NT_body_fld_loc, termset_96, 1, NULL);

static Term termset_97[] = {
	  Term(&NT_nstring, NULL )
	};

static Production production_97( 97, &NT_body_fld_md5, termset_97, 1, NULL);

static Term termset_98[] = {
	  Term(&TT_NUMBER,  &SemanticActions::setPartSize )
	};

static Production production_98( 98, &NT_body_fld_octets, termset_98, 1, NULL);

static Term termset_99[] = {
	  Term(&TT_LPAREN, NULL )
	, Term(&NT_single_body_fld_param, NULL )
	, Term(&NT_km_more_body_fld_param, NULL )
	, Term(&TT_RPAREN, NULL )
	};

static Production production_99( 99, &NT_body_fld_param, termset_99, 4, NULL);

static Term termset_100[] = {
	  Term(&NT_nil, NULL )
	};

static Production production_100( 100, &NT_body_fld_param, termset_100, 1, NULL);

static Term termset_101[] = {
	  Term(&NT_string,  &SemanticActions::setPartParameterName )
	, Term(&TT_SP, NULL )
	, Term(&NT_string,  &SemanticActions::setPartParameterValue )
	};

static Production production_101( 101, &NT_single_body_fld_param, termset_101, 3, NULL);

static Term termset_102[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_single_body_fld_param, NULL )
	, Term(&NT_km_more_body_fld_param, NULL )
	};

static Production production_102( 102, &NT_km_more_body_fld_param, termset_102, 3, NULL);

static Term termset_103[] = {
	};

static Production production_103( 103, &NT_km_more_body_fld_param, termset_103, 0, NULL);

static Term termset_104[] = {
	  Term(&NT_km_one_or_more_bodies,  &SemanticActions::endPartList )
	, Term(&TT_SP, NULL )
	, Term(&NT_media_subtype, NULL )
	, Term(&NT_km_optional_body_ext_mpart, NULL )
	};

static Production production_104( 104, &NT_body_type_mpart, termset_104, 4,  &SemanticActions::beginPartList);

static Term termset_105[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_ext_mpart, NULL )
	};

static Production production_105( 105, &NT_km_optional_body_ext_mpart, termset_105, 2, NULL);

static Term termset_106[] = {
	};

static Production production_106( 106, &NT_km_optional_body_ext_mpart, termset_106, 0, NULL);

static Term termset_107[] = {
	  Term(&NT_body, NULL )
	, Term(&NT_km_zero_or_more_bodies, NULL )
	};

static Production production_107( 107, &NT_km_one_or_more_bodies, termset_107, 2, NULL);

static Term termset_108[] = {
	  Term(&NT_body, NULL )
	, Term(&NT_km_zero_or_more_bodies, NULL )
	};

static Production production_108( 108, &NT_km_zero_or_more_bodies, termset_108, 2, NULL);

static Term termset_109[] = {
	};

static Production production_109( 109, &NT_km_zero_or_more_bodies, termset_109, 0, NULL);

static Term termset_110[] = {
	  Term(&TT_LBRACKET, NULL )
	, Term(&NT_km_optional_section_spec, NULL )
	, Term(&TT_RBRACKET, NULL )
	};

static Production production_110( 110, &NT_section, termset_110, 3, NULL);

static Term termset_111[] = {
	  Term(&NT_section_spec, NULL )
	};

static Production production_111( 111, &NT_km_optional_section_spec, termset_111, 1, NULL);

static Term termset_112[] = {
	  Term(&TT_HEADER,  &SemanticActions::setHeadersSection )
	};

static Production production_112( 112, &NT_section_msgtext, termset_112, 1, NULL);

static Term termset_113[] = {
	  Term(&TT_HEADER_DOT_FIELDS,  &SemanticActions::setHeadersSection )
	, Term(&TT_SP, NULL )
	, Term(&NT_header_list, NULL )
	};

static Production production_113( 113, &NT_section_msgtext, termset_113, 3, NULL);

static Term termset_114[] = {
	  Term(&TT_HEADER_DOT_FIELDS_DOT_NOT, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_header_list, NULL )
	};

static Production production_114( 114, &NT_section_msgtext, termset_114, 3, NULL);

static Term termset_115[] = {
	  Term(&TT_TEXT, NULL )
	};

static Production production_115( 115, &NT_section_msgtext, termset_115, 1, NULL);

static Term termset_116[] = {
	  Term(&NT_nz_number, NULL )
	, Term(&NT_km_section_sub_part, NULL )
	};

static Production production_116( 116, &NT_section_part, termset_116, 2, NULL);

static Term termset_117[] = {
	  Term(&TT_PERIOD, NULL )
	, Term(&NT_nz_number, NULL )
	, Term(&NT_km_section_sub_part, NULL )
	};

static Production production_117( 117, &NT_km_section_sub_part, termset_117, 3, NULL);

static Term termset_118[] = {
	};

static Production production_118( 118, &NT_km_section_sub_part, termset_118, 0, NULL);

static Term termset_119[] = {
	  Term(&NT_section_msgtext, NULL )
	};

static Production production_119( 119, &NT_section_spec, termset_119, 1, NULL);

static Term termset_120[] = {
	  Term(&NT_km_section_part_and_text, NULL )
	};

static Production production_120( 120, &NT_section_spec, termset_120, 1, NULL);

static Term termset_121[] = {
	  Term(&NT_section_part, NULL )
	, Term(&NT_km_optional_dot_section_text, NULL )
	, Term(&NT_km_section_part_and_text, NULL )
	};

static Production production_121( 121, &NT_km_section_part_and_text, termset_121, 3, NULL);

static Term termset_122[] = {
	};

static Production production_122( 122, &NT_km_section_part_and_text, termset_122, 0, NULL);

static Term termset_123[] = {
	  Term(&TT_PERIOD, NULL )
	, Term(&NT_section_text, NULL )
	};

static Production production_123( 123, &NT_km_optional_dot_section_text, termset_123, 2, NULL);

static Term termset_124[] = {
	};

static Production production_124( 124, &NT_km_optional_dot_section_text, termset_124, 0, NULL);

static Term termset_125[] = {
	  Term(&NT_section_msgtext, NULL )
	};

static Production production_125( 125, &NT_section_text, termset_125, 1, NULL);

static Term termset_126[] = {
	  Term(&TT_MIME, NULL )
	};

static Production production_126( 126, &NT_section_text, termset_126, 1, NULL);

static Term termset_127[] = {
	  Term(&NT_string,  &SemanticActions::saveMediaSubtype )
	};

static Production production_127( 127, &NT_media_subtype, termset_127, 1, NULL);

static Term termset_128[] = {
	  Term(&TT_LPAREN, NULL )
	, Term(&NT_header_fld_name, NULL )
	, Term(&NT_km_more_header_field_names, NULL )
	, Term(&TT_RPAREN, NULL )
	};

static Production production_128( 128, &NT_header_list, termset_128, 4, NULL);

static Term termset_129[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_header_fld_name, NULL )
	, Term(&NT_km_more_header_field_names, NULL )
	};

static Production production_129( 129, &NT_km_more_header_field_names, termset_129, 3, NULL);

static Term termset_130[] = {
	};

static Production production_130( 130, &NT_km_more_header_field_names, termset_130, 0, NULL);

static Term termset_131[] = {
	  Term(&NT_astring, NULL )
	};

static Production production_131( 131, &NT_header_fld_name, termset_131, 1, NULL);

static Term termset_132[] = {
	  Term(&NT_string, NULL )
	};

static Production production_132( 132, &NT_astring, termset_132, 1, NULL);

static Term termset_133[] = {
	  Term(&NT_atom_as_string, NULL )
	};

static Production production_133( 133, &NT_astring, termset_133, 1, NULL);

static Term termset_134[] = {
	  Term(&TT_ATOM,  &SemanticActions::saveAtomString )
	};

static Production production_134( 134, &NT_atom_as_string, termset_134, 1, NULL);

static Term termset_135[] = {
	  Term(&TT_NUMBER,  &SemanticActions::saveAtomString )
	};

static Production production_135( 135, &NT_atom_as_string, termset_135, 1, NULL);

static Term termset_136[] = {
	  Term(&TT_TEXT,  &SemanticActions::saveAtomString )
	};

static Production production_136( 136, &NT_atom_as_string, termset_136, 1, NULL);

static Term termset_137[] = {
	  Term(&TT_FETCH,  &SemanticActions::saveAtomString )
	};

static Production production_137( 137, &NT_atom_as_string, termset_137, 1, NULL);

static Term termset_138[] = {
	  Term(&TT_FLAGS,  &SemanticActions::saveAtomString )
	};

static Production production_138( 138, &NT_atom_as_string, termset_138, 1, NULL);

static Term termset_139[] = {
	  Term(&TT_INTERNALDATE,  &SemanticActions::saveAtomString )
	};

static Production production_139( 139, &NT_atom_as_string, termset_139, 1, NULL);

static Term termset_140[] = {
	  Term(&TT_UID,  &SemanticActions::saveAtomString )
	};

static Production production_140( 140, &NT_atom_as_string, termset_140, 1, NULL);

static Term termset_141[] = {
	  Term(&TT_NIL,  &SemanticActions::saveAtomString )
	};

static Production production_141( 141, &NT_atom_as_string, termset_141, 1, NULL);

static Term termset_142[] = {
	  Term(&TT_BODY,  &SemanticActions::saveAtomString )
	};

static Production production_142( 142, &NT_atom_as_string, termset_142, 1, NULL);

static Term termset_143[] = {
	  Term(&TT_BODYSTRUCTURE,  &SemanticActions::saveAtomString )
	};

static Production production_143( 143, &NT_atom_as_string, termset_143, 1, NULL);

static Term termset_144[] = {
	  Term(&TT_ENVELOPE,  &SemanticActions::saveAtomString )
	};

static Production production_144( 144, &NT_atom_as_string, termset_144, 1, NULL);

static Term termset_145[] = {
	  Term(&TT_HEADER,  &SemanticActions::saveAtomString )
	};

static Production production_145( 145, &NT_atom_as_string, termset_145, 1, NULL);

static Term termset_146[] = {
	  Term(&TT_LPAREN, NULL )
	, Term(&NT_env_date, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_env_subject, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_env_from, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_env_sender, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_env_reply_to, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_env_to, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_env_cc, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_env_bcc, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_env_in_reply_to, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_env_message_id, NULL )
	, Term(&TT_RPAREN, NULL )
	};

static Production production_146( 146, &NT_envelope, termset_146, 21, NULL);

static Term termset_147[] = {
	  Term(&NT_km_address_list_or_nil,  &SemanticActions::envBccAddressList )
	};

static Production production_147( 147, &NT_env_bcc, termset_147, 1, NULL);

static Term termset_148[] = {
	  Term(&NT_km_address_list_or_nil,  &SemanticActions::envCcAddressList )
	};

static Production production_148( 148, &NT_env_cc, termset_148, 1, NULL);

static Term termset_149[] = {
	  Term(&TT_LPAREN, NULL )
	, Term(&NT_km_one_or_more_address, NULL )
	, Term(&TT_RPAREN, NULL )
	};

static Production production_149( 149, &NT_km_address_list_or_nil, termset_149, 3,  &SemanticActions::envBeginAddressList);

static Term termset_150[] = {
	  Term(&NT_nil, NULL )
	};

static Production production_150( 150, &NT_km_address_list_or_nil, termset_150, 1,  &SemanticActions::envBeginAddressList);

static Term termset_151[] = {
	  Term(&NT_nstring,  &SemanticActions::envDate )
	};

static Production production_151( 151, &NT_env_date, termset_151, 1, NULL);

static Term termset_152[] = {
	  Term(&NT_km_address_list_or_nil,  &SemanticActions::envFromAddressList )
	};

static Production production_152( 152, &NT_env_from, termset_152, 1, NULL);

static Term termset_153[] = {
	  Term(&NT_nstring,  &SemanticActions::envInReplyTo )
	};

static Production production_153( 153, &NT_env_in_reply_to, termset_153, 1, NULL);

static Term termset_154[] = {
	  Term(&NT_nstring,  &SemanticActions::envMessageId )
	};

static Production production_154( 154, &NT_env_message_id, termset_154, 1, NULL);

static Term termset_155[] = {
	  Term(&NT_km_address_list_or_nil,  &SemanticActions::envReplyToAddressList )
	};

static Production production_155( 155, &NT_env_reply_to, termset_155, 1, NULL);

static Term termset_156[] = {
	  Term(&NT_km_address_list_or_nil,  &SemanticActions::envSenderAddressList )
	};

static Production production_156( 156, &NT_env_sender, termset_156, 1, NULL);

static Term termset_157[] = {
	  Term(&NT_nstring,  &SemanticActions::envSubject )
	};

static Production production_157( 157, &NT_env_subject, termset_157, 1, NULL);

static Term termset_158[] = {
	  Term(&NT_km_address_list_or_nil,  &SemanticActions::envToAddressList )
	};

static Production production_158( 158, &NT_env_to, termset_158, 1, NULL);

static Term termset_159[] = {
	  Term(&NT_address, NULL )
	, Term(&NT_km_zero_or_more_address, NULL )
	};

static Production production_159( 159, &NT_km_one_or_more_address, termset_159, 2, NULL);

static Term termset_160[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_address, NULL )
	, Term(&NT_km_zero_or_more_address, NULL )
	};

static Production production_160( 160, &NT_km_zero_or_more_address, termset_160, 3, NULL);

static Term termset_161[] = {
	  Term(&NT_address, NULL )
	, Term(&NT_km_zero_or_more_address, NULL )
	};

static Production production_161( 161, &NT_km_zero_or_more_address, termset_161, 2, NULL);

static Term termset_162[] = {
	};

static Production production_162( 162, &NT_km_zero_or_more_address, termset_162, 0, NULL);

static Term termset_163[] = {
	  Term(&TT_LPAREN, NULL )
	, Term(&NT_addr_name,  &SemanticActions::envAddrName )
	, Term(&TT_SP, NULL )
	, Term(&NT_addr_adl,  &SemanticActions::envAddrAdl )
	, Term(&TT_SP, NULL )
	, Term(&NT_addr_mailbox,  &SemanticActions::envAddrMailbox )
	, Term(&TT_SP, NULL )
	, Term(&NT_addr_host,  &SemanticActions::envAddrHost )
	, Term(&TT_RPAREN,  &SemanticActions::envEndAddress )
	};

static Production production_163( 163, &NT_address, termset_163, 9, NULL);

static Term termset_164[] = {
	  Term(&NT_nstring, NULL )
	};

static Production production_164( 164, &NT_addr_adl, termset_164, 1, NULL);

static Term termset_165[] = {
	  Term(&NT_nstring, NULL )
	};

static Production production_165( 165, &NT_addr_host, termset_165, 1, NULL);

static Term termset_166[] = {
	  Term(&NT_nstring, NULL )
	};

static Production production_166( 166, &NT_addr_mailbox, termset_166, 1, NULL);

static Term termset_167[] = {
	  Term(&NT_nstring, NULL )
	};

static Production production_167( 167, &NT_addr_name, termset_167, 1, NULL);

static Term termset_168[] = {
	  Term(&TT_MESSAGE_IN_QUOTES,  &SemanticActions::setMimeTypeMessage )
	, Term(&TT_SP, NULL )
	, Term(&NT_km_message_subtype_more, NULL )
	};

static Production production_168( 168, &NT_body_type_msg, termset_168, 3, NULL);

static Term termset_169[] = {
	  Term(&TT_RFC822_IN_QUOTES,  &SemanticActions::setMimeSubtypeRfc822 )
	, Term(&NT_km_body_type_msg_rfc822, NULL )
	};

static Production production_169( 169, &NT_km_message_subtype_more, termset_169, 2, NULL);

static Term termset_170[] = {
	  Term(&NT_quoted_string,  &SemanticActions::setMimeSubtype )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fields, NULL )
	, Term(&NT_km_body_ext_1part, NULL )
	};

static Production production_170( 170, &NT_km_message_subtype_more, termset_170, 4, NULL);

static Term termset_171[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_body_fields, NULL )
	, Term(&NT_km_body_type_msg_ext, NULL )
	};

static Production production_171( 171, &NT_km_body_type_msg_rfc822, termset_171, 3, NULL);

static Term termset_172[] = {
	  Term(&TT_SP, NULL )
	, Term(&NT_km_body_type_msg_ext_gmail, NULL )
	};

static Production production_172( 172, &NT_km_body_type_msg_ext, termset_172, 2, NULL);

static Term termset_173[] = {
	};

static Production production_173( 173, &NT_km_body_type_msg_ext, termset_173, 0, NULL);

static Term termset_174[] = {
	  Term(&NT_km_body_type_msg_ext_rfc822, NULL )
	};

static Production production_174( 174, &NT_km_body_type_msg_ext_gmail, termset_174, 1, NULL);

static Term termset_175[] = {
	  Term(&NT_body_ext_1part, NULL )
	};

static Production production_175( 175, &NT_km_body_type_msg_ext_gmail, termset_175, 1, NULL);

static Term termset_176[] = {
	  Term(&NT_envelope, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_body, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fld_lines,  &SemanticActions::endNestedEmail )
	, Term(&NT_km_body_ext_1part, NULL )
	};

static Production production_176( 176, &NT_km_body_type_msg_ext_rfc822, termset_176, 6,  &SemanticActions::beginNestedEmail);

static Term termset_177[] = {
	  Term(&NT_media_text, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fields, NULL )
	, Term(&TT_SP, NULL )
	, Term(&NT_body_fld_lines, NULL )
	, Term(&NT_km_body_ext_1part, NULL )
	};

static Production production_177( 177, &NT_body_type_text, termset_177, 6, NULL);

static Term termset_178[] = {
	  Term(&NT_quoted_string,  &SemanticActions::setMimeType )
	, Term(&TT_SP, NULL )
	, Term(&NT_quoted_string,  &SemanticActions::setMimeSubtype )
	};

static Production production_178( 178, &NT_media_basic, termset_178, 3, NULL);

static Term termset_179[] = {
	  Term(&TT_MESSAGE_IN_QUOTES,  &SemanticActions::setMimeTypeMessage )
	, Term(&TT_SP, NULL )
	, Term(&TT_RFC822_IN_QUOTES,  &SemanticActions::setMimeSubtypeRfc822 )
	};

static Production production_179( 179, &NT_media_message, termset_179, 3, NULL);

static Term termset_180[] = {
	  Term(&TT_TEXT_IN_QUOTES,  &SemanticActions::setMimeTypeText )
	, Term(&TT_SP, NULL )
	, Term(&NT_media_subtype,  &SemanticActions::setMimeSubtype )
	};

static Production production_180( 180, &NT_media_text, termset_180, 3, NULL);



Symbol* ImapParser::symbols[] = {
	&TT_ERROR
	, &TT_LPAREN
	, &TT_RPAREN
	, &TT_PERIOD
	, &TT_LT
	, &TT_GT
	, &TT_BODY
	, &TT_BODYSTRUCTURE
	, &TT_ENVELOPE
	, &TT_EXPUNGE
	, &TT_FETCH
	, &TT_FLAGS
	, &TT_HEADER
	, &TT_HEADER_DOT_FIELDS
	, &TT_HEADER_DOT_FIELDS_DOT_NOT
	, &TT_INTERNALDATE
	, &TT_MIME
	, &TT_NIL
	, &TT_RFC822
	, &TT_RFC822_DOT_HEADER
	, &TT_RFC822_DOT_SIZE
	, &TT_RFC822_DOT_TEXT
	, &TT_TEXT
	, &TT_UID
	, &TT_LBRACKET
	, &TT_BACKSLASH
	, &TT_NOT_Recent
	, &TT_RBRACKET
	, &TT_LBRACE
	, &TT_RBRACE
	, &TT_ATOM
	, &TT_CR
	, &TT_LF
	, &TT_LITERAL_BYTES
	, &TT_MESSAGE_IN_QUOTES
	, &TT_NUMBER
	, &TT_QUOTED_STRING
	, &TT_QUOTED_STRING_WITHOUT_TERMINATION
	, &TT_RFC822_IN_QUOTES
	, &TT_SP
	, &TT_TEXT_IN_QUOTES
	, &NT_addr_adl
	, &NT_addr_host
	, &NT_addr_mailbox
	, &NT_addr_name
	, &NT_address
	, &NT_astring
	, &NT_atom_as_string
	, &NT_body
	, &NT_body_ext_1part
	, &NT_body_ext_mpart
	, &NT_body_extension
	, &NT_body_fields
	, &NT_body_fld_desc
	, &NT_body_fld_dsp
	, &NT_body_fld_enc
	, &NT_body_fld_id
	, &NT_body_fld_lang
	, &NT_body_fld_lines
	, &NT_body_fld_loc
	, &NT_body_fld_md5
	, &NT_body_fld_octets
	, &NT_body_fld_param
	, &NT_body_type_1part
	, &NT_body_type_basic
	, &NT_body_type_mpart
	, &NT_body_type_msg
	, &NT_body_type_text
	, &NT_date_time
	, &NT_env_bcc
	, &NT_env_cc
	, &NT_env_date
	, &NT_env_from
	, &NT_env_in_reply_to
	, &NT_env_message_id
	, &NT_env_reply_to
	, &NT_env_sender
	, &NT_env_subject
	, &NT_env_to
	, &NT_envelope
	, &NT_flag
	, &NT_flag_extension
	, &NT_flag_fetch
	, &NT_flag_keyword
	, &NT_goal
	, &NT_header_fld_name
	, &NT_header_list
	, &NT_km_address_list_or_nil
	, &NT_km_body_ext_1part
	, &NT_km_body_fld_after_dsp
	, &NT_km_body_fld_after_lang
	, &NT_km_body_fld_after_md5
	, &NT_km_body_or_sect
	, &NT_km_body_type
	, &NT_km_body_type_basic_or_workaround
	, &NT_km_body_type_choices
	, &NT_km_body_type_msg_ext
	, &NT_km_body_type_msg_ext_gmail
	, &NT_km_body_type_msg_ext_rfc822
	, &NT_km_body_type_msg_rfc822
	, &NT_km_body_type_or_ext_mpart
	, &NT_km_flag_fetch_parts
	, &NT_km_message_subtype_more
	, &NT_km_more_body_extension
	, &NT_km_more_body_fld_lang
	, &NT_km_more_body_fld_param
	, &NT_km_more_flag_fetch
	, &NT_km_more_header_field_names
	, &NT_km_more_msg_att
	, &NT_km_one_or_more_address
	, &NT_km_one_or_more_bodies
	, &NT_km_one_part_or_mpart
	, &NT_km_opt_body_extension
	, &NT_km_opt_body_fld_dsp
	, &NT_km_opt_body_fld_lang
	, &NT_km_opt_body_fld_loc
	, &NT_km_optional_body_ext_mpart
	, &NT_km_optional_dot_section_text
	, &NT_km_optional_section_spec
	, &NT_km_section_number
	, &NT_km_section_part_and_text
	, &NT_km_section_sub_part
	, &NT_km_zero_or_more_address
	, &NT_km_zero_or_more_bodies
	, &NT_km_expunge_or_fetch
	, &NT_km_fetch
	, &NT_km_msg_att_dynamic_or_static
	, &NT_literal
	, &NT_media_basic
	, &NT_media_message
	, &NT_media_subtype
	, &NT_media_text
	, &NT_message_data
	, &NT_msg_att
	, &NT_msg_att_dynamic
	, &NT_msg_att_static
	, &NT_nil
	, &NT_nstring
	, &NT_nz_number
	, &NT_quoted_string
	, &NT_section
	, &NT_section_msgtext
	, &NT_section_part
	, &NT_section_spec
	, &NT_section_text
	, &NT_single_body_fld_param
	, &NT_string
	, &NT_uniqueid
};


void ImapParser::initialize(void) {
	NT_goal.setMap(&production_0,&TT_NUMBER);
	NT_message_data.setMap(&production_1,&TT_NUMBER);
	NT_km_expunge_or_fetch.setMap(&production_2,&TT_EXPUNGE);
	NT_km_expunge_or_fetch.setMap(&production_3,&TT_FETCH);
	NT_km_fetch.setMap(&production_4,&TT_FETCH);
	NT_msg_att.setMap(&production_5,&TT_LPAREN);
	NT_km_more_msg_att.setMap(&production_6,&TT_SP);
	NT_km_more_msg_att.setDefault(&production_7);
	NT_km_msg_att_dynamic_or_static.setMap(&production_8,&TT_FLAGS);
	NT_km_msg_att_dynamic_or_static.setMap(&production_9,&TT_INTERNALDATE);
	NT_km_msg_att_dynamic_or_static.setMap(&production_9,&TT_ENVELOPE);
	NT_km_msg_att_dynamic_or_static.setMap(&production_9,&TT_BODY);
	NT_km_msg_att_dynamic_or_static.setMap(&production_9,&TT_RFC822_DOT_SIZE);
	NT_km_msg_att_dynamic_or_static.setMap(&production_9,&TT_UID);
	NT_km_msg_att_dynamic_or_static.setMap(&production_9,&TT_RFC822_DOT_HEADER);
	NT_km_msg_att_dynamic_or_static.setMap(&production_9,&TT_RFC822_DOT_TEXT);
	NT_km_msg_att_dynamic_or_static.setMap(&production_9,&TT_BODYSTRUCTURE);
	NT_km_msg_att_dynamic_or_static.setMap(&production_9,&TT_RFC822);
	NT_msg_att_dynamic.setMap(&production_10,&TT_FLAGS);
	NT_km_flag_fetch_parts.setMap(&production_11,&TT_BACKSLASH);
	NT_km_flag_fetch_parts.setMap(&production_11,&TT_NOT_Recent);
	NT_km_flag_fetch_parts.setMap(&production_11,&TT_ATOM);
	NT_km_flag_fetch_parts.setDefault(&production_12);
	NT_km_more_flag_fetch.setMap(&production_13,&TT_SP);
	NT_km_more_flag_fetch.setDefault(&production_14);
	NT_msg_att_static.setMap(&production_15,&TT_ENVELOPE);
	NT_msg_att_static.setMap(&production_16,&TT_INTERNALDATE);
	NT_msg_att_static.setMap(&production_17,&TT_RFC822);
	NT_msg_att_static.setMap(&production_18,&TT_RFC822_DOT_HEADER);
	NT_msg_att_static.setMap(&production_19,&TT_RFC822_DOT_TEXT);
	NT_msg_att_static.setMap(&production_20,&TT_RFC822_DOT_SIZE);
	NT_msg_att_static.setMap(&production_21,&TT_BODYSTRUCTURE);
	NT_msg_att_static.setMap(&production_22,&TT_BODY);
	NT_msg_att_static.setMap(&production_23,&TT_UID);
	NT_km_body_or_sect.setMap(&production_24,&TT_SP);
	NT_km_body_or_sect.setMap(&production_25,&TT_LBRACKET);
	NT_km_section_number.setMap(&production_26,&TT_LT);
	NT_km_section_number.setDefault(&production_27);
	NT_body.setMap(&production_28,&TT_LPAREN);
	NT_km_one_part_or_mpart.setMap(&production_29,&TT_MESSAGE_IN_QUOTES);
	NT_km_one_part_or_mpart.setMap(&production_29,&TT_QUOTED_STRING);
	NT_km_one_part_or_mpart.setMap(&production_29,&TT_TEXT_IN_QUOTES);
	NT_km_one_part_or_mpart.setMap(&production_30,&TT_LPAREN);
	NT_body_type_1part.setMap(&production_31,&TT_MESSAGE_IN_QUOTES);
	NT_body_type_1part.setMap(&production_31,&TT_QUOTED_STRING);
	NT_body_type_1part.setMap(&production_31,&TT_TEXT_IN_QUOTES);
	NT_km_body_ext_1part.setMap(&production_32,&TT_SP);
	NT_km_body_ext_1part.setDefault(&production_33);
	NT_km_body_type_choices.setMap(&production_34,&TT_QUOTED_STRING);
	NT_km_body_type_choices.setMap(&production_35,&TT_MESSAGE_IN_QUOTES);
	NT_km_body_type_choices.setMap(&production_36,&TT_TEXT_IN_QUOTES);
	NT_body_type_basic.setMap(&production_37,&TT_QUOTED_STRING);
	NT_km_body_type_basic_or_workaround.setMap(&production_38,&TT_QUOTED_STRING);
	NT_km_body_type_or_ext_mpart.setMap(&production_39,&TT_QUOTED_STRING);
	NT_km_body_type_or_ext_mpart.setMap(&production_40,&TT_LPAREN);
	NT_km_body_type_or_ext_mpart.setMap(&production_40,&TT_NIL);
	NT_km_body_type.setMap(&production_41,&TT_QUOTED_STRING);
	NT_body_fields.setMap(&production_42,&TT_LPAREN);
	NT_body_fields.setMap(&production_42,&TT_NIL);
	NT_body_fld_dsp.setMap(&production_43,&TT_LPAREN);
	NT_body_fld_dsp.setMap(&production_44,&TT_NIL);
	NT_body_ext_1part.setMap(&production_45,&TT_MESSAGE_IN_QUOTES);
	NT_body_ext_1part.setMap(&production_45,&TT_LBRACE);
	NT_body_ext_1part.setMap(&production_45,&TT_QUOTED_STRING);
	NT_body_ext_1part.setMap(&production_45,&TT_TEXT_IN_QUOTES);
	NT_body_ext_1part.setMap(&production_45,&TT_RFC822_IN_QUOTES);
	NT_body_ext_1part.setMap(&production_45,&TT_NIL);
	NT_body_ext_mpart.setMap(&production_46,&TT_LPAREN);
	NT_body_ext_mpart.setMap(&production_46,&TT_NIL);
	NT_km_opt_body_fld_dsp.setMap(&production_47,&TT_SP);
	NT_km_opt_body_fld_dsp.setDefault(&production_48);
	NT_km_opt_body_fld_lang.setMap(&production_49,&TT_SP);
	NT_km_opt_body_fld_lang.setDefault(&production_50);
	NT_km_opt_body_fld_loc.setMap(&production_51,&TT_SP);
	NT_km_opt_body_fld_loc.setDefault(&production_52);
	NT_km_opt_body_extension.setMap(&production_53,&TT_SP);
	NT_km_opt_body_extension.setDefault(&production_54);
	NT_km_body_fld_after_md5.setMap(&production_55,&TT_SP);
	NT_km_body_fld_after_md5.setDefault(&production_56);
	NT_km_body_fld_after_dsp.setMap(&production_57,&TT_SP);
	NT_km_body_fld_after_dsp.setDefault(&production_58);
	NT_km_body_fld_after_lang.setMap(&production_59,&TT_SP);
	NT_km_body_fld_after_lang.setDefault(&production_60);
	NT_body_extension.setMap(&production_61,&TT_MESSAGE_IN_QUOTES);
	NT_body_extension.setMap(&production_61,&TT_LBRACE);
	NT_body_extension.setMap(&production_61,&TT_QUOTED_STRING);
	NT_body_extension.setMap(&production_61,&TT_TEXT_IN_QUOTES);
	NT_body_extension.setMap(&production_61,&TT_RFC822_IN_QUOTES);
	NT_body_extension.setMap(&production_61,&TT_NIL);
	NT_body_extension.setMap(&production_62,&TT_NUMBER);
	NT_body_extension.setMap(&production_63,&TT_LPAREN);
	NT_body_extension.setDefault(&production_64);
	NT_km_more_body_extension.setMap(&production_65,&TT_SP);
	NT_km_more_body_extension.setDefault(&production_66);
	NT_body_fld_desc.setMap(&production_67,&TT_MESSAGE_IN_QUOTES);
	NT_body_fld_desc.setMap(&production_67,&TT_LBRACE);
	NT_body_fld_desc.setMap(&production_67,&TT_QUOTED_STRING);
	NT_body_fld_desc.setMap(&production_67,&TT_TEXT_IN_QUOTES);
	NT_body_fld_desc.setMap(&production_67,&TT_RFC822_IN_QUOTES);
	NT_body_fld_desc.setMap(&production_67,&TT_NIL);
	NT_nstring.setMap(&production_68,&TT_MESSAGE_IN_QUOTES);
	NT_nstring.setMap(&production_68,&TT_LBRACE);
	NT_nstring.setMap(&production_68,&TT_QUOTED_STRING);
	NT_nstring.setMap(&production_68,&TT_TEXT_IN_QUOTES);
	NT_nstring.setMap(&production_68,&TT_RFC822_IN_QUOTES);
	NT_nstring.setMap(&production_69,&TT_NIL);
	NT_nil.setMap(&production_70,&TT_NIL);
	NT_quoted_string.setMap(&production_71,&TT_QUOTED_STRING);
	NT_string.setMap(&production_72,&TT_QUOTED_STRING);
	NT_string.setMap(&production_73,&TT_TEXT_IN_QUOTES);
	NT_string.setMap(&production_74,&TT_RFC822_IN_QUOTES);
	NT_string.setMap(&production_75,&TT_MESSAGE_IN_QUOTES);
	NT_string.setMap(&production_76,&TT_LBRACE);
	NT_literal.setMap(&production_77,&TT_LBRACE);
	NT_nz_number.setMap(&production_78,&TT_NUMBER);
	NT_uniqueid.setMap(&production_79,&TT_NUMBER);
	NT_date_time.setMap(&production_80,&TT_QUOTED_STRING);
	NT_flag.setMap(&production_81,&TT_ATOM);
	NT_flag.setMap(&production_82,&TT_BACKSLASH);
	NT_flag_extension.setMap(&production_83,&TT_BACKSLASH);
	NT_flag_fetch.setMap(&production_84,&TT_BACKSLASH);
	NT_flag_fetch.setMap(&production_84,&TT_ATOM);
	NT_flag_fetch.setMap(&production_85,&TT_NOT_Recent);
	NT_flag_keyword.setMap(&production_86,&TT_ATOM);
	NT_body_fld_enc.setMap(&production_87,&TT_MESSAGE_IN_QUOTES);
	NT_body_fld_enc.setMap(&production_87,&TT_LBRACE);
	NT_body_fld_enc.setMap(&production_87,&TT_QUOTED_STRING);
	NT_body_fld_enc.setMap(&production_87,&TT_TEXT_IN_QUOTES);
	NT_body_fld_enc.setMap(&production_87,&TT_RFC822_IN_QUOTES);
	NT_body_fld_enc.setMap(&production_88,&TT_NIL);
	NT_body_fld_id.setMap(&production_89,&TT_MESSAGE_IN_QUOTES);
	NT_body_fld_id.setMap(&production_89,&TT_LBRACE);
	NT_body_fld_id.setMap(&production_89,&TT_QUOTED_STRING);
	NT_body_fld_id.setMap(&production_89,&TT_TEXT_IN_QUOTES);
	NT_body_fld_id.setMap(&production_89,&TT_RFC822_IN_QUOTES);
	NT_body_fld_id.setMap(&production_89,&TT_NIL);
	NT_body_fld_lang.setMap(&production_90,&TT_MESSAGE_IN_QUOTES);
	NT_body_fld_lang.setMap(&production_90,&TT_LBRACE);
	NT_body_fld_lang.setMap(&production_90,&TT_QUOTED_STRING);
	NT_body_fld_lang.setMap(&production_90,&TT_TEXT_IN_QUOTES);
	NT_body_fld_lang.setMap(&production_90,&TT_RFC822_IN_QUOTES);
	NT_body_fld_lang.setMap(&production_90,&TT_NIL);
	NT_body_fld_lang.setMap(&production_91,&TT_LPAREN);
	NT_body_fld_lang.setDefault(&production_92);
	NT_km_more_body_fld_lang.setMap(&production_93,&TT_SP);
	NT_km_more_body_fld_lang.setDefault(&production_94);
	NT_body_fld_lines.setMap(&production_95,&TT_NUMBER);
	NT_body_fld_loc.setMap(&production_96,&TT_MESSAGE_IN_QUOTES);
	NT_body_fld_loc.setMap(&production_96,&TT_LBRACE);
	NT_body_fld_loc.setMap(&production_96,&TT_QUOTED_STRING);
	NT_body_fld_loc.setMap(&production_96,&TT_TEXT_IN_QUOTES);
	NT_body_fld_loc.setMap(&production_96,&TT_RFC822_IN_QUOTES);
	NT_body_fld_loc.setMap(&production_96,&TT_NIL);
	NT_body_fld_md5.setMap(&production_97,&TT_MESSAGE_IN_QUOTES);
	NT_body_fld_md5.setMap(&production_97,&TT_LBRACE);
	NT_body_fld_md5.setMap(&production_97,&TT_QUOTED_STRING);
	NT_body_fld_md5.setMap(&production_97,&TT_TEXT_IN_QUOTES);
	NT_body_fld_md5.setMap(&production_97,&TT_RFC822_IN_QUOTES);
	NT_body_fld_md5.setMap(&production_97,&TT_NIL);
	NT_body_fld_octets.setMap(&production_98,&TT_NUMBER);
	NT_body_fld_param.setMap(&production_99,&TT_LPAREN);
	NT_body_fld_param.setMap(&production_100,&TT_NIL);
	NT_single_body_fld_param.setMap(&production_101,&TT_MESSAGE_IN_QUOTES);
	NT_single_body_fld_param.setMap(&production_101,&TT_LBRACE);
	NT_single_body_fld_param.setMap(&production_101,&TT_QUOTED_STRING);
	NT_single_body_fld_param.setMap(&production_101,&TT_TEXT_IN_QUOTES);
	NT_single_body_fld_param.setMap(&production_101,&TT_RFC822_IN_QUOTES);
	NT_km_more_body_fld_param.setMap(&production_102,&TT_SP);
	NT_km_more_body_fld_param.setDefault(&production_103);
	NT_body_type_mpart.setMap(&production_104,&TT_LPAREN);
	NT_km_optional_body_ext_mpart.setMap(&production_105,&TT_SP);
	NT_km_optional_body_ext_mpart.setDefault(&production_106);
	NT_km_one_or_more_bodies.setMap(&production_107,&TT_LPAREN);
	NT_km_zero_or_more_bodies.setMap(&production_108,&TT_LPAREN);
	NT_km_zero_or_more_bodies.setDefault(&production_109);
	NT_section.setMap(&production_110,&TT_LBRACKET);
	NT_km_optional_section_spec.setMap(&production_111,&TT_HEADER_DOT_FIELDS_DOT_NOT);
	NT_km_optional_section_spec.setMap(&production_111,&TT_HEADER);
	NT_km_optional_section_spec.setMap(&production_111,&TT_HEADER_DOT_FIELDS);
	NT_km_optional_section_spec.setMap(&production_111,&TT_TEXT);
	NT_km_optional_section_spec.setMap(&production_111,&TT_NUMBER);
	NT_km_optional_section_spec.setDefault(&production_111);
	NT_section_msgtext.setMap(&production_112,&TT_HEADER);
	NT_section_msgtext.setMap(&production_113,&TT_HEADER_DOT_FIELDS);
	NT_section_msgtext.setMap(&production_114,&TT_HEADER_DOT_FIELDS_DOT_NOT);
	NT_section_msgtext.setMap(&production_115,&TT_TEXT);
	NT_section_part.setMap(&production_116,&TT_NUMBER);
	NT_km_section_sub_part.setMap(&production_117,&TT_PERIOD);
	NT_km_section_sub_part.setDefault(&production_118);
	NT_section_spec.setMap(&production_119,&TT_HEADER_DOT_FIELDS_DOT_NOT);
	NT_section_spec.setMap(&production_119,&TT_HEADER);
	NT_section_spec.setMap(&production_119,&TT_HEADER_DOT_FIELDS);
	NT_section_spec.setMap(&production_119,&TT_TEXT);
	NT_section_spec.setMap(&production_120,&TT_NUMBER);
	NT_section_spec.setDefault(&production_120);
	NT_km_section_part_and_text.setMap(&production_121,&TT_NUMBER);
	NT_km_section_part_and_text.setDefault(&production_122);
	NT_km_optional_dot_section_text.setMap(&production_123,&TT_PERIOD);
	NT_km_optional_dot_section_text.setDefault(&production_124);
	NT_section_text.setMap(&production_125,&TT_HEADER_DOT_FIELDS_DOT_NOT);
	NT_section_text.setMap(&production_125,&TT_HEADER);
	NT_section_text.setMap(&production_125,&TT_HEADER_DOT_FIELDS);
	NT_section_text.setMap(&production_125,&TT_TEXT);
	NT_section_text.setMap(&production_126,&TT_MIME);
	NT_media_subtype.setMap(&production_127,&TT_MESSAGE_IN_QUOTES);
	NT_media_subtype.setMap(&production_127,&TT_LBRACE);
	NT_media_subtype.setMap(&production_127,&TT_QUOTED_STRING);
	NT_media_subtype.setMap(&production_127,&TT_TEXT_IN_QUOTES);
	NT_media_subtype.setMap(&production_127,&TT_RFC822_IN_QUOTES);
	NT_header_list.setMap(&production_128,&TT_LPAREN);
	NT_km_more_header_field_names.setMap(&production_129,&TT_SP);
	NT_km_more_header_field_names.setDefault(&production_130);
	NT_header_fld_name.setMap(&production_131,&TT_LBRACE);
	NT_header_fld_name.setMap(&production_131,&TT_BODY);
	NT_header_fld_name.setMap(&production_131,&TT_FETCH);
	NT_header_fld_name.setMap(&production_131,&TT_RFC822_IN_QUOTES);
	NT_header_fld_name.setMap(&production_131,&TT_HEADER);
	NT_header_fld_name.setMap(&production_131,&TT_UID);
	NT_header_fld_name.setMap(&production_131,&TT_TEXT);
	NT_header_fld_name.setMap(&production_131,&TT_NUMBER);
	NT_header_fld_name.setMap(&production_131,&TT_BODYSTRUCTURE);
	NT_header_fld_name.setMap(&production_131,&TT_MESSAGE_IN_QUOTES);
	NT_header_fld_name.setMap(&production_131,&TT_INTERNALDATE);
	NT_header_fld_name.setMap(&production_131,&TT_ENVELOPE);
	NT_header_fld_name.setMap(&production_131,&TT_QUOTED_STRING);
	NT_header_fld_name.setMap(&production_131,&TT_TEXT_IN_QUOTES);
	NT_header_fld_name.setMap(&production_131,&TT_NIL);
	NT_header_fld_name.setMap(&production_131,&TT_ATOM);
	NT_header_fld_name.setMap(&production_131,&TT_FLAGS);
	NT_astring.setMap(&production_132,&TT_MESSAGE_IN_QUOTES);
	NT_astring.setMap(&production_132,&TT_LBRACE);
	NT_astring.setMap(&production_132,&TT_QUOTED_STRING);
	NT_astring.setMap(&production_132,&TT_TEXT_IN_QUOTES);
	NT_astring.setMap(&production_132,&TT_RFC822_IN_QUOTES);
	NT_astring.setMap(&production_133,&TT_INTERNALDATE);
	NT_astring.setMap(&production_133,&TT_ENVELOPE);
	NT_astring.setMap(&production_133,&TT_BODY);
	NT_astring.setMap(&production_133,&TT_FETCH);
	NT_astring.setMap(&production_133,&TT_HEADER);
	NT_astring.setMap(&production_133,&TT_UID);
	NT_astring.setMap(&production_133,&TT_NIL);
	NT_astring.setMap(&production_133,&TT_ATOM);
	NT_astring.setMap(&production_133,&TT_TEXT);
	NT_astring.setMap(&production_133,&TT_NUMBER);
	NT_astring.setMap(&production_133,&TT_BODYSTRUCTURE);
	NT_astring.setMap(&production_133,&TT_FLAGS);
	NT_atom_as_string.setMap(&production_134,&TT_ATOM);
	NT_atom_as_string.setMap(&production_135,&TT_NUMBER);
	NT_atom_as_string.setMap(&production_136,&TT_TEXT);
	NT_atom_as_string.setMap(&production_137,&TT_FETCH);
	NT_atom_as_string.setMap(&production_138,&TT_FLAGS);
	NT_atom_as_string.setMap(&production_139,&TT_INTERNALDATE);
	NT_atom_as_string.setMap(&production_140,&TT_UID);
	NT_atom_as_string.setMap(&production_141,&TT_NIL);
	NT_atom_as_string.setMap(&production_142,&TT_BODY);
	NT_atom_as_string.setMap(&production_143,&TT_BODYSTRUCTURE);
	NT_atom_as_string.setMap(&production_144,&TT_ENVELOPE);
	NT_atom_as_string.setMap(&production_145,&TT_HEADER);
	NT_envelope.setMap(&production_146,&TT_LPAREN);
	NT_env_bcc.setMap(&production_147,&TT_LPAREN);
	NT_env_bcc.setMap(&production_147,&TT_NIL);
	NT_env_cc.setMap(&production_148,&TT_LPAREN);
	NT_env_cc.setMap(&production_148,&TT_NIL);
	NT_km_address_list_or_nil.setMap(&production_149,&TT_LPAREN);
	NT_km_address_list_or_nil.setMap(&production_150,&TT_NIL);
	NT_env_date.setMap(&production_151,&TT_MESSAGE_IN_QUOTES);
	NT_env_date.setMap(&production_151,&TT_LBRACE);
	NT_env_date.setMap(&production_151,&TT_QUOTED_STRING);
	NT_env_date.setMap(&production_151,&TT_TEXT_IN_QUOTES);
	NT_env_date.setMap(&production_151,&TT_RFC822_IN_QUOTES);
	NT_env_date.setMap(&production_151,&TT_NIL);
	NT_env_from.setMap(&production_152,&TT_LPAREN);
	NT_env_from.setMap(&production_152,&TT_NIL);
	NT_env_in_reply_to.setMap(&production_153,&TT_MESSAGE_IN_QUOTES);
	NT_env_in_reply_to.setMap(&production_153,&TT_LBRACE);
	NT_env_in_reply_to.setMap(&production_153,&TT_QUOTED_STRING);
	NT_env_in_reply_to.setMap(&production_153,&TT_TEXT_IN_QUOTES);
	NT_env_in_reply_to.setMap(&production_153,&TT_RFC822_IN_QUOTES);
	NT_env_in_reply_to.setMap(&production_153,&TT_NIL);
	NT_env_message_id.setMap(&production_154,&TT_MESSAGE_IN_QUOTES);
	NT_env_message_id.setMap(&production_154,&TT_LBRACE);
	NT_env_message_id.setMap(&production_154,&TT_QUOTED_STRING);
	NT_env_message_id.setMap(&production_154,&TT_TEXT_IN_QUOTES);
	NT_env_message_id.setMap(&production_154,&TT_RFC822_IN_QUOTES);
	NT_env_message_id.setMap(&production_154,&TT_NIL);
	NT_env_reply_to.setMap(&production_155,&TT_LPAREN);
	NT_env_reply_to.setMap(&production_155,&TT_NIL);
	NT_env_sender.setMap(&production_156,&TT_LPAREN);
	NT_env_sender.setMap(&production_156,&TT_NIL);
	NT_env_subject.setMap(&production_157,&TT_MESSAGE_IN_QUOTES);
	NT_env_subject.setMap(&production_157,&TT_LBRACE);
	NT_env_subject.setMap(&production_157,&TT_QUOTED_STRING);
	NT_env_subject.setMap(&production_157,&TT_TEXT_IN_QUOTES);
	NT_env_subject.setMap(&production_157,&TT_RFC822_IN_QUOTES);
	NT_env_subject.setMap(&production_157,&TT_NIL);
	NT_env_to.setMap(&production_158,&TT_LPAREN);
	NT_env_to.setMap(&production_158,&TT_NIL);
	NT_km_one_or_more_address.setMap(&production_159,&TT_LPAREN);
	NT_km_zero_or_more_address.setMap(&production_160,&TT_SP);
	NT_km_zero_or_more_address.setMap(&production_161,&TT_LPAREN);
	NT_km_zero_or_more_address.setDefault(&production_162);
	NT_address.setMap(&production_163,&TT_LPAREN);
	NT_addr_adl.setMap(&production_164,&TT_MESSAGE_IN_QUOTES);
	NT_addr_adl.setMap(&production_164,&TT_LBRACE);
	NT_addr_adl.setMap(&production_164,&TT_QUOTED_STRING);
	NT_addr_adl.setMap(&production_164,&TT_TEXT_IN_QUOTES);
	NT_addr_adl.setMap(&production_164,&TT_RFC822_IN_QUOTES);
	NT_addr_adl.setMap(&production_164,&TT_NIL);
	NT_addr_host.setMap(&production_165,&TT_MESSAGE_IN_QUOTES);
	NT_addr_host.setMap(&production_165,&TT_LBRACE);
	NT_addr_host.setMap(&production_165,&TT_QUOTED_STRING);
	NT_addr_host.setMap(&production_165,&TT_TEXT_IN_QUOTES);
	NT_addr_host.setMap(&production_165,&TT_RFC822_IN_QUOTES);
	NT_addr_host.setMap(&production_165,&TT_NIL);
	NT_addr_mailbox.setMap(&production_166,&TT_MESSAGE_IN_QUOTES);
	NT_addr_mailbox.setMap(&production_166,&TT_LBRACE);
	NT_addr_mailbox.setMap(&production_166,&TT_QUOTED_STRING);
	NT_addr_mailbox.setMap(&production_166,&TT_TEXT_IN_QUOTES);
	NT_addr_mailbox.setMap(&production_166,&TT_RFC822_IN_QUOTES);
	NT_addr_mailbox.setMap(&production_166,&TT_NIL);
	NT_addr_name.setMap(&production_167,&TT_MESSAGE_IN_QUOTES);
	NT_addr_name.setMap(&production_167,&TT_LBRACE);
	NT_addr_name.setMap(&production_167,&TT_QUOTED_STRING);
	NT_addr_name.setMap(&production_167,&TT_TEXT_IN_QUOTES);
	NT_addr_name.setMap(&production_167,&TT_RFC822_IN_QUOTES);
	NT_addr_name.setMap(&production_167,&TT_NIL);
	NT_body_type_msg.setMap(&production_168,&TT_MESSAGE_IN_QUOTES);
	NT_km_message_subtype_more.setMap(&production_169,&TT_RFC822_IN_QUOTES);
	NT_km_message_subtype_more.setMap(&production_170,&TT_QUOTED_STRING);
	NT_km_body_type_msg_rfc822.setMap(&production_171,&TT_SP);
	NT_km_body_type_msg_ext.setMap(&production_172,&TT_SP);
	NT_km_body_type_msg_ext.setDefault(&production_173);
	NT_km_body_type_msg_ext_gmail.setMap(&production_174,&TT_LPAREN);
	NT_km_body_type_msg_ext_gmail.setMap(&production_175,&TT_MESSAGE_IN_QUOTES);
	NT_km_body_type_msg_ext_gmail.setMap(&production_175,&TT_LBRACE);
	NT_km_body_type_msg_ext_gmail.setMap(&production_175,&TT_QUOTED_STRING);
	NT_km_body_type_msg_ext_gmail.setMap(&production_175,&TT_TEXT_IN_QUOTES);
	NT_km_body_type_msg_ext_gmail.setMap(&production_175,&TT_RFC822_IN_QUOTES);
	NT_km_body_type_msg_ext_gmail.setMap(&production_175,&TT_NIL);
	NT_km_body_type_msg_ext_rfc822.setMap(&production_176,&TT_LPAREN);
	NT_body_type_text.setMap(&production_177,&TT_TEXT_IN_QUOTES);
	NT_media_basic.setMap(&production_178,&TT_QUOTED_STRING);
	NT_media_message.setMap(&production_179,&TT_MESSAGE_IN_QUOTES);
	NT_media_text.setMap(&production_180,&TT_TEXT_IN_QUOTES);
}
